services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: nbfc_db
      POSTGRES_USER: nbfc_user
      POSTGRES_PASSWORD: nbfc_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nbfc_user -d nbfc_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: tauqeerops/nbfc-django-api:latest  # Use pre-built image
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Override for Docker environment
      - DB_HOST=db
      - DB_USER=nbfc_user
      - DB_PASSWORD=nbfc_password
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    volumes:
      - static_volume:/app/staticfiles  # Only mount data volumes
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    # Follow exact instructions: migrate -> runserver (superuser created manually)

volumes:
  postgres_data:
  static_volume:
  media_volume:
