version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://nbfc_user:nbfc_password@db:5432/nbfc_db
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=*
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true

volumes:
  static_volume:
  media_volume:
